settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: src
  path: .
  commands:
    install:
      status: true
      method: go build -o /opt/server
    run:
      status: true
      method: /opt/server
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
